### ISSUE TITLE
How feature complete is this libary?

### ISSUE THREAD

**Issue by helpermethod** [jsdf/react-ratchet#1]

**Comment by jsdf** [comment]
I'd say about 30%. I have a bunch of widgets still to implement, and I have to figure out how best to expose the transition animations. Writing some tests would be a good idea too. Hopefully I'll get most of that done over the next month.

**Comment by hellogerard** [comment]
You answered this in Feb. What is the answer today?

**Comment by jsdf** [comment]
I don't have time to actively work on this library at the moment. I'm still using it for a personal project, so I'm not going to abandon it, but I'm not building new components any time soon.
